language: python

python:
  - "2.6"
  - "2.7"

env:
  - DJANGO=Django==1.4.3
  # - DJANGO=https://www.djangoproject.com/download/1.5c1/tarball/

# command to install dependencies, initialize database
install:
  - pip install -q $DJANGO --use-mirrors
  - pip install -r requirements.txt --use-mirrors
  - python setup.py install
  - newspeak init
  - newspeak syncdb --migrate --noinput

# command to run tests
script: newspeak test newspeak
