language: python

python:
  - "2.6"
  - "2.7"

env:
  - DJANGO=Django==1.4.8
  - DJANGO=Django==1.5.4

# command to install dependencies, initialize database
install:
  - pip install -q $DJANGO --use-mirrors
  - pip install -r requirements.txt --use-mirrors
  - python setup.py install
  - newspeak init

# command to run tests
script: newspeak test --logging-level=INFO
